### ISSUE TITLE
Example 4 boundary conditions.

### ISSUE THREAD

**Issue by mrclary** [connortannahill/bacoli_py#8]
Hi, I don't understand how you constructed the boundary conditions and jacobians for the boundary conditions in example 4.
* First, can you help me understand why the boundary values are `bval[0] = u[0] - 1.0` instead of `bval[0] = 0` when the problem states `u([0, 1], t) = 0`?
* Second, I don't know what the "Jacobian for the boundary condition" is or how to determine it; could explain that to me?

Thanks.

**Comment by connortannahill** [comment]
With regards to the first question, the documentation at the beginning of this example states that u(0, t) = 1 and u(1, t) = 1 are the boundary conditions. Each of the BC's must be given to the solver in the form of an implicit function `b(t, u, u_x) = 0`, so `bval[0] = u[0] - 1.0` is the correct way to impose this BC.

Secondly, what we mean by the Jacobian is actually three Jacobians matrices db(t, u, u_x)/du, db(t, u, u_x)/du_x, and db(t, u, u_x)/dt, where b(t, u, u_x) is LHS of the implicit BC function (so it would be 'b(t, u, u_x) = u[0] - 1.0' in this case). For this example where we are solving a single PDE, the Jacobians are simply the partial derivatives of `b(t, u, u_x)` with respect to `u`, `u_x` and `t`. 

Also note that the Jacobians are optional. In the standard Fortran version of the solver they can speed up performance somewhat, but in this Python version their use comes with some additional overhead that seems to eliminate any benefit.

Connor

**Comment by mrclary** [comment]
@connortannahill , Thank you very much for the prompt reply!
> Each of the BC's must be given to the solver in the form of an implicit function `b(t, u, u_x) = 0`

It all makes perfect sense now...
